services:
  gpt-researcher:
    container_name: gpt-researcher
    build: ./
    env_file: stack.env
    restart: always
    ports:
      - 10005:8000
  gptr-nextjs:
    container_name: gptr-nextjs
    pull_policy: build
    image: gptresearcher/gptr-nextjs
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend/nextjs
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    restart: no
    ports:
      - 10006:3000

volumes:
  node_modules: {}
  app: {}