FROM node:18.17.0-alpine
WORKDIR /app
# Copy package.json and package-lock.json (if available)
COPY package*.json ./
RUN npm install --legacy-peer-deps
# Copy the rest of the application code
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
